version: "3.8"
services:
  phpmyadmin:
    image: docker.io/library/phpmyadmin:latest
    hostname: ${WARDEN_ENV_NAME}-phpmyadmin
    domainname: phpmyadmin.${WARDEN_ENV_NAME}.test
    environment:
      - PMA_HOSTS=${WARDEN_ENV_NAME}-db-1
      - PMA_USER=root
      - PMA_PASSWORD=magento
      - PMA_ABSOLUTE_URI=https://phpmyadmin.${TRAEFIK_DOMAIN}
    labels:
      - "traefik.http.routers.${WARDEN_ENV_NAME}-phpmyadmin.tls=true"
      - "traefik.enable=true"
      - "traefik.http.middlewares.pma-suffixes.chain.middlewares=pma-suffix"
      - "traefik.http.routers.${WARDEN_ENV_NAME}-phpmyadmin.rule=(Host(`${TRAEFIK_DOMAIN}`)&&PathPrefix(`/phpmyadmin`))||Host(`phpmyadmin.${WARDEN_ENV_NAME}.warden.test`)"
      - "traefik.http.routers.${WARDEN_ENV_NAME}-phpmyadmin.middlewares=pma-suffixes@docker"
      - "traefik.http.middlewares.pma-suffix.replacepathregex.regex=^/phpmyadmin/(.*)"
      - "traefik.http.middlewares.pma-suffix.replacepathregex.replacement=/$$1"
    volumes:
      - ./var/log/pma-logs:/var/log/apache2
  nginx:
    volumes:
      - ./.warden/nginx/custom.conf:/etc/nginx/default.d/custom.conf:ro
      - ./.warden/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
      - ./.warden/nginx/magento2.conf:/etc/nginx/available.d/magento2.conf:ro
    labels:
      - traefik.http.routers.${WARDEN_ENV_NAME}-nginx.rule=
        HostRegexp(`{subdomain:.+}.${TRAEFIK_DOMAIN}`)
        || Host(`${TRAEFIK_DOMAIN}`)
        || Host(`clear.magento2.loc`)
        || (Host(`443-${CLEAR_URL:-clear.magento2.loc}`)&&PathPrefix(`/`))
      # Вирубаємо tls для контейнера
      - "traefik.http.routers.${WARDEN_ENV_NAME}-nginx.tls=true"
      # Робимо загальний набір middlewares щоб потім прописати його як "traefik.http.routers.${WARDEN_ENV_NAME}-nginx.middlewares=gitpod-suffixes@docker"
      - "traefik.http.middlewares.gitpod-suffixes.chain.middlewares=https-redirect"
      # Приміняємо увесь chain міддлевейру до контейнеру з nginx
      - "traefik.http.routers.${WARDEN_ENV_NAME}-nginx.middlewares=gitpod-suffixes@docker"
      - "traefik.http.middlewares.https-redirect.headers.customrequestheaders.X-Forwarded-Proto=https"
#    environment:
#      - XDEBUG_CONNECT_BACK_HOST=192.168.32.1
  php-fpm:
    volumes:
      - ~/.ssh/known_hosts:/home/www-data/.ssh/known_hosts:ro
      - ~/.ssh/id_rsa:/home/www-data/.ssh/id_rsa:ro
      - ~/.ssh/id_rsa.pub:/home/www-data/.ssh/id_rsa.pub:ro
      - ../:/var/project:ro
    extra_hosts:
      - clear.magento2.loc:${TRAEFIK_ADDRESS:-0.0.0.0}
  php-debug:
    volumes:
      - ~/.ssh/known_hosts:/home/www-data/.ssh/known_hosts:ro
      - ~/.ssh/id_rsa:/home/www-data/.ssh/id_rsa:ro
      - ~/.ssh/id_rsa.pub:/home/www-data/.ssh/id_rsa.pub:ro
      - ../:/var/project:ro
    extra_hosts:
      - clear.magento2.loc:${TRAEFIK_ADDRESS:-0.0.0.0}
  db:
    command:
      --innodb-buffer-pool-size=8G
      --innodb-ft-cache-size=256M
      --max_connections=200
      --connect_timeout=28800
      --wait_timeout=28800
      --max_allowed_packet=16M
      --thread_cache_size=128
      --sort_buffer_size=4M
      --bulk_insert_buffer_size=16M
      --tmp_table_size=32M
      --max_heap_table_size=32M
      --query_cache_limit=128K
      --query_cache_size=16M

